version: '3.8'

services:
  db:
    image: mysql:5.7
    # Use root/example as user/password credentials
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=plym
    volumes:
      - ./data/db:/var/lib/mysql:z

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
        - db
  app:
    build: .
    container_name: api-python
    restart: on-failure
    ports: 8000:8000
    env_file:
      - ./.env
    depends_on:
        - db
    volumes:
      - ./:/app/:z

