name: Build and Deploy Workflow
on: [push]
jobs:
  Build-and-Deploy:
    env:
      database_hostname: mysql
      database_port: 3306
      database_username: root
      database_password: remo
      database_name: plym
      database_sqlite: sqlite:///./sql_app.db

      api_title: Plym Content API
      api_version: 0.0.8
      api_description: API for CRUD Content in Plym App
      api_contact_name: Romulo Menezes
      api_contact_email: romulojnr@gmail.com
      api_contact_url: http://localhost
      api_licence: licenca
      api_terms: termos

      jwt_exp_time: 30
      jwt_secret_key: plym
      jwt_algorithm: HS256

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_PASSWORD: remo
          MYSQL_DB: plym
        ports:
        - 3306:3306
        # needed because the mysql container does not provide a healthcheck
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -v -s parte10/tests
          