name: MySQL Test
on: [push]
jobs:
  MySQL-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE plym;'
